spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/movies?useSSL=false  # Add this if using MySQL 8+
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update  # Change to 'validate' or 'none' in production
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: "palayan785@gmail.com"
    password: "ncer mahj vrnj alxt"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

project:
  poster: D:/1WebTap/Spring/movieApi/poster/  # Ensure this path exists

base:
  url: "http://localhost:8080"

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
